// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwZp_hcc5L8npGm2W3yVYoIx4ZlaguvA',
    appId: '1:267687971564:web:0e9ed6ace16af7f96133c9',
    messagingSenderId: '267687971564',
    projectId: 'beebyte-98cba',
    authDomain: 'beebyte-98cba.firebaseapp.com',
    storageBucket: 'beebyte-98cba.appspot.com',
    measurementId: 'G-EJRV1HT8FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtHUzQrOFkYF5DRAqM0uerxpR5gv8PNY',
    appId: '1:267687971564:android:23fe1e5b88ccf6d76133c9',
    messagingSenderId: '267687971564',
    projectId: 'beebyte-98cba',
    storageBucket: 'beebyte-98cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_S1Vsb6s3FooT31nogwHWKQ5QpKp1FwQ',
    appId: '1:267687971564:ios:c32c6c08be4f13b06133c9',
    messagingSenderId: '267687971564',
    projectId: 'beebyte-98cba',
    storageBucket: 'beebyte-98cba.appspot.com',
    iosBundleId: 'com.example.denemeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMwZp_hcc5L8npGm2W3yVYoIx4ZlaguvA',
    appId: '1:267687971564:web:2bb903fe961bc4486133c9',
    messagingSenderId: '267687971564',
    projectId: 'beebyte-98cba',
    authDomain: 'beebyte-98cba.firebaseapp.com',
    storageBucket: 'beebyte-98cba.appspot.com',
    measurementId: 'G-3EG3W287XE',
  );
}
